plugins {
    id 'com.android.application'
}

android {
    namespace "org.luanti.luanti" // <-- ОСТАВЬ СВОЁ, ЕСЛИ МЕНЯЛ
    compileSdk 34 // или 35, если у тебя стоит выше

    // ВОТ ОНА, НАША СПАСИТЕЛЬНАЯ СТРОЧКА:
    ndkVersion "25.2.9519653"

    defaultConfig {
        applicationId "org.luanti.luanti" // <-- ОСТАВЬ СВОЁ, ЕСЛИ МЕНЯЛ
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    externalNativeBuild {
        cmake {
            path "../../CMakeLists.txt"
            version "3.22.1"
        }
    }
    
    sourceSets {
        main {
            jniLibs.srcDirs = ['../native/deps/lib']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation project(':native')
}
